version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 572370687270.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t coworking1:$CODEBUILDTAG .
      - docker tag coworking1:$CODEBUILDTAG 572370687270.dkr.ecr.us-east-1.amazonaws.com/coworking1:$CODEBUILDTAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 572370687270.dkr.ecr.us-east-1.amazonaws.com/coworking1:$CODEBUILDTAG
      - echo Tagging the image as latest...
      - docker tag 572370687270.dkr.ecr.us-east-1.amazonaws.com/coworking1:$CODEBUILDTAG 572370687270.dkr.ecr.us-east-1.amazonaws.com/coworking1:latest
      - docker push 572370687270.dkr.ecr.us-east-1.amazonaws.com/coworking1:latest

artifacts:
  files:
    - '**/*'
